// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEm91M8su8bt9tVzl8RvVdkizgUDsbe2w',
    appId: '1:77897826950:web:00741572722573a2e48707',
    messagingSenderId: '77897826950',
    projectId: 'pertemuan9-15298',
    authDomain: 'pertemuan9-15298.firebaseapp.com',
    storageBucket: 'pertemuan9-15298.firebasestorage.app',
    measurementId: 'G-5BSX1QW0TV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIRCAqOPWrm3G6e1jzbHBLXjGENCeC508',
    appId: '1:77897826950:android:0f2d1f731f92b3c9e48707',
    messagingSenderId: '77897826950',
    projectId: 'pertemuan9-15298',
    storageBucket: 'pertemuan9-15298.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFyIXZ2L7qPBLD9mxugBLP_APE-5nnPLs',
    appId: '1:77897826950:ios:05a548854f700336e48707',
    messagingSenderId: '77897826950',
    projectId: 'pertemuan9-15298',
    storageBucket: 'pertemuan9-15298.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFyIXZ2L7qPBLD9mxugBLP_APE-5nnPLs',
    appId: '1:77897826950:ios:05a548854f700336e48707',
    messagingSenderId: '77897826950',
    projectId: 'pertemuan9-15298',
    storageBucket: 'pertemuan9-15298.firebasestorage.app',
    iosBundleId: 'com.example.pertemuan9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEm91M8su8bt9tVzl8RvVdkizgUDsbe2w',
    appId: '1:77897826950:web:fd1f3847e42ff59ee48707',
    messagingSenderId: '77897826950',
    projectId: 'pertemuan9-15298',
    authDomain: 'pertemuan9-15298.firebaseapp.com',
    storageBucket: 'pertemuan9-15298.firebasestorage.app',
    measurementId: 'G-HTCLD3CE26',
  );
}
